### PR TITLE
Docker Build

### PR DESCRIPTION
**Pull request by larkmullins**

### CODE REVIEW

**Comment by jlaswell** [comment]
Is there not a Dockerfile that needs to go along with this? I can see the build step for release, but I'm not seeing where the container is built out. (I may be missing something specific to CI that handles that?)

**Comment by larkmullins** [comment]
The `internal/docker-push` is the Dockerfile that builds out the image and pushes to Docker Hub. This is an internal step provided from Wercker.

**Comment by jlaswell** [comment]
Got it. That all makes a lot more sense now. lgtm!

As an aside, does that mean that the `.git` directory is committed here too?

**Comment by larkmullins** [comment]
That's a good point. There is no `docker ignore` that I can see in Wercker's docs. Let me see if I can add a step to remove the `.git` dir and other files/dirs we might want to remove before building the image.

**Comment by larkmullins** [comment]
Ok, image is now being built and removing .git directory. We can remove others as well if we want. This is good for review.

**Comment by kyleferguson** [comment]
We can add a task for this later, but really there shouldn't be any reason to have the source code on the container, or if we do, have a separate `-dev` tag that does. Keep the container as slim as possible.

**Comment by jlaswell** [comment]
I was trying to make this happen on Friday, but having trouble with running brizo on scratch... I think it may have to do with it being started via a cli command.

**Comment by kyleferguson** [comment]
That shouldn't have impact on the ability to run. Likely a configuration issue. When Brizo starts it verifies a connection to the database and connection to Kube. If one of those fail it won't run.

**Comment by jlaswell** [comment]
Ah, I keep forgetting that. good point

**Comment by larkmullins** [comment]
It would be easy to remove the source. I will make a PR for the source to be removed.

**Pull request merged**
